phoenix:
  build: ./web
web:
  extends:
    service: phoenix
  ports:
    - '4000:4000'
  links:
    - postgres
  command: mix phoenix.server
ecto-setup:
  extends: 
    service: phoenix 
  links:
   - postgres
  command: mix ecto.create && mix ecto.migrate
postgres:
  image: postgres
  environment:
    POSTGRES_PASSWORD: 'ilovecoffee'
mqtt-client:
  build: ./mqtt-client
  links:
   - mqtt-broker
   - postgres
mqtt-broker:
  image: toke/mosquitto
  ports:
   - '1883:1883'
   - '9001:9001'
mock-machine:
  build: ./mock-machine
  links:
   - mqtt-broker
