web:
  build: ./web
  command: sh start.sh
  ports:
    - '4000:4000'
  links:
    - postgres
  volumes:
    - './web:/code'
  working_dir: '/code'
postgres:
  image: postgres
  environment:
    POSTGRES_PASSWORD: 'ilovecoffee'
mqtt-client:
  build: ./mqtt-client
  links:
   - mqtt-broker
mqtt-broker:
  image: toke/mosquitto
  ports:
   - '1883:1883'
   - '9001:9001'
